#!/usr/bin/env python
import sys


def swap(first, second):
    with open(first) as f1, open(second) as f2:
        file1 = f1.read()
        file2 = f2.read()

    with open(first, 'w+') as f1, open(second, 'w+') as f2:
        f1.write(file2)
        f2.write(file1)


if __name__ == '__main__':
    usage = 'swap <file> <file>'.format(sys.argv[0])
    try:
        swap(sys.argv[1], sys.argv[2])
    except Exception:
        sys.exit(usage)
